# Site settings
title: 0PT1MATES
email: jm@0pt1mates.com
description: "Building solutions to release the power of data."
baseurl: ""
url: "http://www.0pt1mates.com"
username: 0pt1mates

# Build settings
markdown: kramdown
permalink: pretty
