# Site settings
title: 0PT1MATES
email: jm@0pt1mates.com
description: "Building solutions to release the power of data.<br/>Proven expertise delivering solutions with Scala, XML and Cloud Computing."
baseurl: ""
url: "http://www.0pt1mates.com"
username: 0pt1mates
company: 0PT1MATES LTD

# Build settings
markdown: kramdown
permalink: pretty
